Document: libaedaemon
Title: Debian libaedaemon Manual
Author: <insert document author here>
Abstract: This manual describes what libaedaemon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libaedaemon/libaedaemon.sgml.gz

Format: postscript
Files: /usr/share/doc/libaedaemon/libaedaemon.ps.gz

Format: text
Files: /usr/share/doc/libaedaemon/libaedaemon.text.gz

Format: HTML
Index: /usr/share/doc/libaedaemon/html/index.html
Files: /usr/share/doc/libaedaemon/html/*.html
